#name: Add issue to project
#on:
#  issues:
#    types:
#      - opened   
#      
#jobs:
#  track_issues_dispatch:
#    name: Add new issue to project
#    uses: DUNE-DAQ/.github/.github/workflows/track_new_issues.yml@develop
#    secrets:
#      BOT_CI_ISSUES: ${{ secrets.BOT_CI_ISSUES }}
